### ISSUE TITLE
Eagle Issue: Example for using Eagle with transcription

### ISSUE THREAD

**Issue by ichbinjon** [Picovoice/eagle#87]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice Eagle docs
- [X] I have searched the existing issues for Eagle

### SDK

iOS

### Eagle package version

1.0.0

### Framework version

1.0.0

### Platform

iOS

### OS/Browser version

18

### Describe the bug

Is there an example on how to use this along with transcription frameworks?
I'd like to have a labelled transcription like:

Sam: Hey, good morning
Joel: Hey what's up
Jim: Hey guys, how's it going?

If there's no example, some pointers on how one would go about doing it would be awesome.

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by albho** [comment]
Hey @ichbinjon, consider using [Leopard-iOS](https://github.com/Picovoice/leopard/tree/master/binding/ios) ([demo](https://github.com/Picovoice/leopard/tree/master/demo/ios)) for transcription. Leopard has built-in speaker diarization. If you only need speaker diarization, use [Falcon-iOS](https://github.com/Picovoice/falcon/tree/main/binding/ios) ([demo](https://github.com/Picovoice/falcon/tree/main/demo/ios)) instead of Eagle.
